### ISSUE TITLE
Add callback guards

### ISSUE THREAD

**Issue by MaulingMonkey** [MaulingMonkey/thindx-xaudio2#16]
* [ ] [It is invalid to call DestroyVoice from within a callback](https://learn.microsoft.com/en-us/windows/win32/api/xaudio2/nf-xaudio2-ixaudio2voice-destroyvoice#remarks), so panic instead
* [x] It is undefined behavior to panic=unwind over an FFI boundary, so catch and/or or seppuku the process instead

**Comment by shinmao** [comment]
Hi, I think the potential risk of panic still exists in the code of `xaudio2_thread_guard()`.
https://github.com/MaulingMonkey/thindx-xaudio2/blob/a9239a82bf2715c65566087e1e690170dd021199/crates/thindx-xaudio2/src/util/_util.rs#L19
Based on the documentation of `eprintln!()`, this function will trigger panic when writing to `std::err` failed. I think we should use something that could return `Result` to avoid panic.

Maybe we can directly invoke this function https://doc.rust-lang.org/std/io/struct.StderrLock.html#method.write?

How do you think about it?

**Comment by MaulingMonkey** [comment]
Good catch!
